jenkins:
  container_name: jenkins_ctn
  image: gnostrenoff/jenkins:latest
  links:
    - dind
  ports:
    - 8080:8080
 
dind:
  container_name: dind_ctn
  image: gnostrenoff/dind:latest
  expose:
    - 4242
  environment:
    PORT: 4242
  privileged: true
